### ISSUE TITLE
New re-design of the interface for a one table design. 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#100]
This issue is related to the following issues #85 #90: 

The current design contains two tables: 

- The first table describes the sample information and annotation. 

<img width="1069" alt="Screen Shot 2019-04-30 at 10 19 49" src="https://user-images.githubusercontent.com/52113/56952206-ac4fef00-6b31-11e9-97f7-6d15f225d1ce.png">

- The second table defines the `real` experimental design and the relation: 

**sample id -> faction id -> file**

<img width="1047" alt="Screen Shot 2019-04-30 at 10 20 03" src="https://user-images.githubusercontent.com/52113/56952303-f1742100-6b31-11e9-9fe5-961e0e9b9365.png">

The current design force the user to provides the fraction + sample id + file and force also to define the properties related with it.

**Comment by davco6** [comment]
These are my impression about why could be more useful to deal with one single table instead of two:

First, with one single table we give more freedom to the user for setting the table. This way it's the user who is responsible of select their own columns order.

Second, I think that for expertise user (in terms of the tool) could be useful to have two tables (it reduces the redundant information) but for beginners it is more straightforward to have only one table. At the end, usually on the publications there is only one excel table that contain the metadata of each raw file.

Third, although this is not a double-table issue, it is for this current design. It is very important to have the Sample Name column and the samples be named by the user (this could be the same name as the raw file or not -in case of multiplexing analysis-) and this should appear always on the screen (I mean the column Sample Name should be fixed).
